<template>
  <div>
    <van-tabbar route>
      <van-tabbar-item
        replace
        to="/Nav"
        icon="home-o"
      >
        首页
      </van-tabbar-item>
      <van-tabbar-item
        replace
        to="/Petcircle"
        icon="search"
      >
        宠圈
      </van-tabbar-item>
      <van-tabbar-item
        replace
        to="/Addstory"
        icon="search"
      >
        发布
      </van-tabbar-item>
      <van-tabbar-item
        replace
        to="/Addstory"
        icon="search"
      >
        消息
      </van-tabbar-item>
      <van-tabbar-item
        replace
        to="/Addstory"
        icon="search"
      >
        我的
      </van-tabbar-item>
    </van-tabbar>
  </div>
</template>